{
  "type": "AVRO",
  "schema": "{\"type\":\"record\",\"name\":\"ETF\",\"fields\":[{\"name\":\"date\",\"type\":[\"string\",\"null\"]},{\"name\":\"price\",\"type\":[\"string\",\"null\"]}]}",
  "properties": {}
}
